### ISSUE TITLE
Unity Crashing

### ISSUE THREAD

**Issue by JT514569** [JT514569/2DInfiniteJumper#1]
![Screenshot 2024-03-27 030621](https://github.com/JT514569/2DInfiniteJumper/assets/104973800/49f7f754-0423-4b4a-9296-616d28ae55c1)

The project crashes when I'm trying to load it. The screenshot shows it right before it boots me to the Unity bug reporter.
It seems to crash when it gets to the script compilers.
I'm currently using the same version as the one we use at College. I deleted the DA thing as well inside the game's assets folder so I'm quite confused on how this happens. I don't know how I'd exactly put the newton soft in with this issue.

**Comment by purna** [comment]
Delete the following folders from your project
Library 
Packages
Logs

Unity will recreate them for you.

Or delete the whole project and download again from github. (i've deleted the folder with the error from Github)


<img width="976" alt="Screenshot 2024-03-28 at 13 04 06" src="https://github.com/JT514569/2DInfiniteJumper/assets/29038/0e9f8639-c55f-43aa-aee2-9c41a0ae89ac">

Either open from GitHub Desktop or select the open in github desktop option on the repo
